name: Cancel Workflow
description: Candel the current workflow

branding:
  color: orange
  icon: stop-circle

inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    required: true

runs:
  using: node12
  main: dist/index.js
